### ISSUE TITLE
abus_get_current_url() causes switch user request to hang on Pantheon

### ISSUE THREAD

**Issue by 6foot5** [drazenbebic/admin-bar-user-switching#1]
The issue is that this function generates the current URL, and always includes the $_SERVER[ 'SERVER_PORT' ] component if it is something other than 80. On Pantheon, and similar web application setups, the PHP application port is different than the one displayed to the end user, which results in an incorrect URL.

I would suggest perhaps using a different method to identify the active URL, or provide a WP filter that allows other plugins to customize the behavior of this function.

As a temporary work-around, we've modified our local copy of this function to always set the port component of the URL to an empty string.

**Comment by drazenbebic** [comment]
Hello @6foot5 

thanks for reporting this. I have marked it as a bug and will include a fix for the next patch-version. Although I'm not really sure what to do about this, but at the very least I will provide a filter.

**Comment by 6foot5** [comment]
Thank you for the quick response, and also for maintaining such a useful plugin!

**Comment by shakethatweight-simon** [comment]
@6foot5 I don't use Pantheon, but I've got an idea how this might be solved. Can you share the output of `var_dump($_SERVER)` to show us what values are available.

**Comment by 6foot5** [comment]
[pantheon SERVER dump.txt](https://github.com/drazenbebic/admin-bar-user-switching/files/5245970/pantheon.SERVER.dump.txt)

@shakethatweight-simon Thanks for looking into this. I've attached the output of var_dump($_SERVER) for you to check out. I've obviously obscured/removed all secret or identifiable info, but hopefully the key names will give you an idea what's available on Pantheon. Let me know if more info would help.

**Comment by shakethatweight-simon** [comment]
@6foot5  I was hoping for something along the lines of FORWARDED_PORT or something else to indicate the PORT the application is running on vs the port that the user is connected to. I'll do some research later.

**Comment by 6foot5** [comment]
@shakethatweight-simon It looks like Pantheon give us ["SERVER_PORT"] and ["REMOTE_PORT"]. I do not see any other port-related values available.

**Comment by shakethatweight-simon** [comment]
@6foot5 
> Pantheon give us `["SERVER_PORT"]` and `["REMOTE_PORT"]`

Unfortunately REMOTE_PORT isn't useful to us, and SERVER_PORT is the one the code is already trying to use (incorrectly in your case).

**Comment by drazenbebic** [comment]
@6foot5 @shakethatweight-simon 

Hi guys, thanks for the input so far!

I'm thinking that there is no right way to do this for everyone. Instead, I'll just wrap the function in a filter and allow you to modify the URL before it's being returned. 

That sound good enough?

**Comment by drazenbebic** [comment]
PS: If someone else would like to do it, I'd be more than happy to merge a PR.

**Comment by shakethatweight-simon** [comment]
> PS: If someone else would like to do it, I'd be more than happy to merge a PR.

Ha ha, ok, I get the hint, I'll push something up to you in a couple of moments.

**Comment by shakethatweight-simon** [comment]
@drazenbebic  Pull request submitted.

**Comment by drazenbebic** [comment]
@shakethatweight-simon thanks a bunch, PR has been merged :)
